run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

linters-settings:
  goimports:
    local-prefixes: github.com/your-org/design-ai
  
  gocyclo:
    min-complexity: 20  # 放宽复杂度限制
  
  dupl:
    threshold: 100
  
  goconst:
    min-len: 3
    min-occurrences: 3
    
  revive:
    min-confidence: 0.8

linters:
  enable:
    - goimports
    - revive      # 替代golint
    - govet
    - errcheck
    - staticcheck
    - unused      # 替代structcheck, varcheck, deadcode
    - gosimple
    - ineffassign
    - typecheck
    - gocyclo
    - gofmt
    - misspell
    - goconst
    - unparam
    - nakedret
    - prealloc
    - exportloopref  # 替代scopelint
  
  disable:
    - lll

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - path: database/seed\.go
      linters:
        - errcheck
    - path: handlers/
      linters:
        - gocyclo  # 暂时忽略handlers的复杂度
  
  exclude-use-default: false
  max-same-issues: 0
  new: false