run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

linters-settings:
  goimports:
    local-prefixes: github.com/oldweipro/design-ai
  
  gocyclo:
    min-complexity: 25  # 进一步放宽复杂度限制
  
  dupl:
    threshold: 150

linters:
  enable:
    - goimports
    - govet        # Go官方代码检查
    - errcheck     # 检查未处理的错误
    - staticcheck  # 静态分析检查
    - unused       # 检查未使用的代码
    - gosimple     # 简化代码建议
    - ineffassign  # 检查无效赋值
    - typecheck    # 类型检查
    - gofmt        # 代码格式检查
    - misspell     # 拼写检查
  
  disable:
    - revive       # 禁用过于严格的代码风格检查
    - gocyclo      # 禁用复杂度检查
    - goconst      # 禁用常量检查
    - unparam      # 禁用未使用参数检查
    - nakedret     # 禁用naked return检查
    - prealloc     # 禁用预分配检查
    - lll          # 行长度限制

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - path: database/seed\.go
      linters:
        - errcheck
    # 忽略注释相关的警告
    - text: "should have comment"
      linters:
        - revive
    - text: "comment on exported"
      linters:
        - revive
    - text: "package comment"
      linters:
        - revive
  
  exclude-use-default: true
  max-same-issues: 0
  new: false